'use client';

import React, { useState } from 'react';
import {
  Copy,
  Check,
  Star,
  Download,
  Flame,
  FileText,
  Tag,
  Hash,
  Clock,
  Sparkles,
  Zap,
  TrendingUp,
  Share2,
  Edit3,
  Lightbulb,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  RotateCw,
  Target,
  Crown,
  Eye,
  ShieldCheck,
} from 'lucide-react';
import { MetadataResult, GeneratedTitle } from '@/types';
import { GENRE_LABELS } from '@/lib/phonkKnowledge';
import { ShortsPreviewMockup } from './ShortsPreviewMockup';
import { AudioSyncCalculator } from './AudioSyncCalculator';
import { RetentionTimeline } from './RetentionTimeline';
import { TitleBattleArena } from './TitleBattleArena';
import { VisualEditBlueprintCard } from './VisualEditBlueprintCard';

interface OutputResultsProps {
  result: MetadataResult;
  onToggleFavorite?: (id: string) => void;
  onReRoll?: () => void;
  isLoading?: boolean;
  onOpenThumbnailStudio?: () => void;
  onOpenAudit?: () => void;
  onShowToast: (text: string, type?: 'success' | 'error' | 'info') => void;
}

export const OutputResults: React.FC<OutputResultsProps> = ({
  result,
  onToggleFavorite,
  onReRoll,
  isLoading,
  onOpenThumbnailStudio,
  onOpenAudit,
  onShowToast,
}) => {
  const [copiedTitleIndex, setCopiedTitleIndex] = useState<number | null>(null);
  const [selectedPreviewTitleIdx, setSelectedPreviewTitleIdx] = useState<number>(0);
  const [copiedDesc, setCopiedDesc] = useState(false);
  const [copiedTags, setCopiedTags] = useState(false);
  const [copiedHashtags, setCopiedHashtags] = useState(false);
  const [copiedMaster, setCopiedMaster] = useState(false);
  const [isEditingDesc, setIsEditingDesc] = useState(false);
  const [editedDescription, setEditedDescription] = useState(result.description);

  React.useEffect(() => {
    setEditedDescription(result.description);
    setIsEditingDesc(false);
  }, [result]);

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    onShowToast(`Copied ${label} to clipboard!`, 'success');
  };

  const handleCopyTitle = (title: string, index: number) => {
    copyToClipboard(title, 'Title');
    setCopiedTitleIndex(index);
    setTimeout(() => setCopiedTitleIndex(null), 2000);
  };

  const handleCopyDescription = () => {
    copyToClipboard(editedDescription, 'Description');
    setCopiedDesc(true);
    setTimeout(() => setCopiedDesc(false), 2000);
  };

  const handleCopyTags = () => {
    copyToClipboard(result.tagsFormatted, 'YouTube Studio Tags');
    setCopiedTags(true);
    setTimeout(() => setCopiedTags(false), 2000);
  };

  const handleCopyHashtags = () => {
    copyToClipboard(result.hashtags.join(' '), 'Hashtags');
    setCopiedHashtags(true);
    setTimeout(() => setCopiedHashtags(false), 2000);
  };

  const handleMasterCopy = () => {
    const bestTitle = result.titles[0]?.title || '';
    const masterExport = `━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🎯 TITLE (Top 1M+ Views Winner):
${bestTitle}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📝 DESCRIPTION (Paste into YouTube Studio):
${editedDescription}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🏷️ TAGS (Paste into YouTube Studio Tags box):
${result.tagsFormatted}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#️⃣ HASHTAGS:
${result.hashtags.join(' ')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔥 VIRAL PROBABILITY:
${result.viralProbability?.percentage || 92}% (${result.viralProbability?.tierLabel || 'High Potential'})

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⏰ BEST UPLOAD TIME:
${result.bestUploadTime.peakHoursIST}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;

    copyToClipboard(masterExport, 'Full YouTube Metadata Package');
    setCopiedMaster(true);
    setTimeout(() => setCopiedMaster(false), 2500);
  };

  const handleExportFile = () => {
    const bestTitle = result.titles[0]?.title || '';
    const fileContent = `# YouTube Metadata Export - ${bestTitle}
Generated by PhnkEditz YT Booster on ${new Date(result.timestamp).toLocaleString()}

## Viral Probability Score: ${result.viralProbability?.percentage || 92}% [${result.viralProbability?.tierLabel || 'High Potential'}]

## Ranked Video Titles for 1 Million Views
${result.titles.map((t, idx) => `${idx + 1}. ${t.title}\n   [${t.millionViewsPotential?.badge || t.hookType}] (${t.charCount} chars)\n   Why it hits 1M: ${t.millionViewsPotential?.whyItHits1M || 'High CTR hook'}`).join('\n\n')}

## SEO Description
${editedDescription}

## YouTube Studio Tags (${result.tagsCharCount} / 500 chars)
${result.tagsFormatted}

## Hashtags
${result.hashtags.join(' ')}

## Kya Daalna Chahiye (DO's)
${(result.dosAndDonts?.dos || []).map((d) => `- ✅ ${d.title}: ${d.reason}`).join('\n')}

## Kya NAHI Daalna Chahiye (DONT's)
${(result.dosAndDonts?.donts || []).map((d) => `- ❌ ${d.title}: ${d.reason}`).join('\n')}

## Upload Timing Insight
Peak Hours (IST): ${result.bestUploadTime.peakHoursIST}
Peak Hours (EST): ${result.bestUploadTime.peakHoursEST}
`;

    const blob = new Blob([fileContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `phnkeditz-metadata-${Date.now()}.md`;
    link.click();
    URL.revokeObjectURL(url);
    onShowToast('Metadata exported as Markdown file!', 'success');
  };

  const viralPercent = result.viralProbability?.percentage || 92;

  return (
    <div className="space-y-6">
      {/* VIRAL CHANCE / PROBABILITY METER */}
      <div className="bg-gradient-to-br from-red-950/40 via-zinc-900 to-purple-950/40 rounded-2xl p-5 border border-red-500/40 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-48 h-48 bg-phonk-accent/10 rounded-full blur-3xl pointer-events-none" />

        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-zinc-800/80">
          <div className="flex items-center gap-3">
            <div className="relative flex items-center justify-center w-16 h-16 rounded-2xl bg-zinc-950 border border-red-500/50 shrink-0 shadow-lg shadow-red-950/50">
              <div className="text-center">
                <span className="text-xl font-black text-red-400 leading-none">
                  {viralPercent}%
                </span>
                <span className="text-[9px] block text-zinc-400 font-bold uppercase tracking-wider">Chance</span>
              </div>
            </div>
            <div>
              <div className="flex items-center gap-2 flex-wrap">
                <h3 className="text-base font-black text-white flex items-center gap-1.5">
                  <Flame className="w-4 h-4 text-phonk-accent animate-pulse fill-phonk-accent" />
                  Viral Breakout Probability
                </h3>
                <span className="px-2 py-0.5 text-[10px] font-extrabold uppercase rounded-md bg-red-500/20 text-red-300 border border-red-500/30">
                  {result.viralProbability?.tier === 'ULTRA_VIRAL' ? '🔥 Ultra High Chance' : '⚡ Strong Potential'}
                </span>
              </div>
              <p className="text-xs text-zinc-400 mt-0.5">
                {result.viralProbability?.tierLabel || 'High Viral Potential for YouTube Shorts Algorithm'}
              </p>
            </div>
          </div>

          {/* Re-Roll & Audit Buttons */}
          <div className="flex items-center gap-2 flex-wrap">
            {onOpenAudit && (
              <button
                onClick={onOpenAudit}
                className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-emerald-600/20 hover:bg-emerald-600/30 border border-emerald-500/40 text-xs font-bold text-emerald-300 transition-all shrink-0"
              >
                <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                <span>1M Views Audit</span>
              </button>
            )}

            {onReRoll && (
              <button
                onClick={onReRoll}
                disabled={isLoading}
                className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-zinc-800/90 hover:bg-zinc-700 border border-zinc-700 text-xs font-bold text-zinc-100 hover:text-white transition-all transform active:scale-95 shadow-md group shrink-0"
                title="Generate fresh new variations of titles, description, tags and thumbnails"
              >
                <RotateCw className={`w-3.5 h-3.5 text-cyan-400 group-hover:rotate-180 transition-transform ${isLoading ? 'animate-spin' : ''}`} />
                <span>{isLoading ? 'Re-Rolling...' : '🔄 Re-Roll'}</span>
              </button>
            )}
          </div>
        </div>

        {/* Probability Factors Breakdown */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 pt-3.5 text-xs">
          {(result.viralProbability?.factors || [
            { label: 'Hook Power', score: 96, desc: 'Swipe stopper' },
            { label: 'Tag Density', score: 98, desc: '500-char match' },
            { label: 'Trend Velocity', score: 95, desc: 'High demand' },
            { label: 'Audio Sync Index', score: 92, desc: 'Sound ID' },
          ]).map((factor, i) => (
            <div key={i} className="p-2.5 bg-zinc-950/70 rounded-xl border border-zinc-800/70 space-y-1">
              <div className="flex items-center justify-between">
                <span className="text-[11px] font-semibold text-zinc-400">{factor.label}</span>
                <span className="text-[10px] font-bold text-emerald-400">{factor.score}%</span>
              </div>
              <p className="text-[10px] text-zinc-500 truncate">{factor.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Master Action & SEO Score Bar */}
      <div className="bg-glass-card rounded-2xl p-5 border border-zinc-800 shadow-2xl relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          {/* SEO Score Visual */}
          <div className="flex items-center gap-4">
            <div className="relative flex items-center justify-center w-14 h-14 rounded-2xl bg-zinc-900 border border-zinc-800 shrink-0">
              <div className="text-center">
                <span className="text-lg font-black text-emerald-400 leading-none">
                  {result.seoScore}
                </span>
                <span className="text-[9px] block text-zinc-500 font-bold">/ 100</span>
              </div>
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-sm sm:text-base font-bold text-white">Algorithm SEO Power</h3>
                <span className="px-2 py-0.5 text-[10px] font-extrabold rounded-md bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                  Ready for YouTube Studio
                </span>
              </div>
              <div className="flex flex-wrap items-center gap-3 text-xs text-zinc-400 mt-1">
                <span>
                  Titles: <strong className="text-zinc-200">{result.seoBreakdown.titlePower}%</strong>
                </span>
                <span>•</span>
                <span>
                  Tags: <strong className="text-zinc-200">{result.seoBreakdown.tagCoverage}%</strong>
                </span>
                <span>•</span>
                <span>
                  Description: <strong className="text-zinc-200">{result.seoBreakdown.descriptionRichness}%</strong>
                </span>
              </div>
            </div>
          </div>

          {/* Master Buttons */}
          <div className="flex flex-wrap items-center gap-2 sm:gap-2.5">
            <button
              onClick={handleMasterCopy}
              className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-phonk-accent to-red-600 hover:from-red-500 hover:to-phonk-accent text-white text-xs sm:text-sm font-bold shadow-lg shadow-phonk-accent/25 transition-all transform active:scale-95"
            >
              {copiedMaster ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              <span>{copiedMaster ? 'All Metadata Copied!' : 'Copy All for Upload'}</span>
            </button>

            {onToggleFavorite && (
              <button
                onClick={() => onToggleFavorite(result.id)}
                className={`p-2.5 rounded-xl border text-xs font-semibold transition-all ${
                  result.isFavorite
                    ? 'bg-amber-500/15 border-amber-500 text-amber-400'
                    : 'bg-zinc-900 border-zinc-800 text-zinc-400 hover:text-amber-400 hover:border-amber-500/40'
                }`}
                title={result.isFavorite ? 'Remove from favorites' : 'Save to favorites'}
              >
                <Star className={`w-4 h-4 ${result.isFavorite ? 'fill-amber-400' : ''}`} />
              </button>
            )}

            <button
              onClick={handleExportFile}
              className="p-2.5 rounded-xl bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 hover:border-zinc-700 text-zinc-400 hover:text-white transition-all"
              title="Download Markdown Report"
            >
              <Download className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* STRATEGY ADVISOR: Kya Daalein vs Kya Na Daalein (DOs & DONTs) */}
      <div className="bg-glass-card rounded-2xl p-5 sm:p-6 border border-zinc-800/80 shadow-xl space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-amber-500/10 text-amber-400">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm sm:text-base font-bold text-white flex items-center gap-2">
                Algorithm Growth Guide (Kya Daalein vs Kya Na Daalein)
              </h3>
              <p className="text-xs text-zinc-400">
                1k views ceiling break karne ke liye zaroori rules aur common mistakes
              </p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* DO's Card */}
          <div className="p-4 bg-emerald-950/20 border border-emerald-500/30 rounded-xl space-y-3">
            <div className="flex items-center gap-2 pb-2 border-b border-emerald-500/20">
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
              <h4 className="text-xs font-bold uppercase tracking-wider text-emerald-300">
                ✅ Ye Zaroor Daalein (DO's)
              </h4>
            </div>

            {/* High-CTR Thumbnail Text Ideas */}
            <div className="bg-glass-card rounded-2xl p-5 border border-zinc-800/80 shadow-xl space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="p-1.5 rounded-lg bg-red-500/10 text-red-400">
                    <Lightbulb className="w-4 h-4" />
                  </div>
                  <h3 className="text-sm font-bold text-white">Thumbnail Text Hooks</h3>
                </div>

                {onOpenThumbnailStudio && (
                  <button
                    onClick={onOpenThumbnailStudio}
                    className="flex items-center gap-1.5 px-3 py-1 bg-red-600/20 hover:bg-red-600/30 border border-red-500/40 text-red-300 rounded-lg text-xs font-bold transition-all"
                  >
                    <span>🎨 Create Image Card</span>
                  </button>
                )}
              </div>
              <div className="grid grid-cols-2 gap-2">
                {result.thumbnailHooks.map((hook, i) => (
                  <button
                    key={i}
                    onClick={() => copyToClipboard(hook, 'Thumbnail Text')}
                    className="p-3 bg-zinc-950/90 hover:bg-zinc-900 border border-zinc-800 hover:border-red-500/40 rounded-xl text-xs font-black text-zinc-100 hover:text-red-400 text-center transition-all flex items-center justify-center gap-1.5"
                  >
                    <span>{hook}</span>
                  </button>
                ))}
              </div>
              <p className="text-[11px] text-zinc-400 leading-relaxed">
                Click any hook to copy or click <strong>🎨 Create Image Card</strong> to render &amp; download 4K PNG thumbnail!
              </p>
            </div>
            
            <ul className="space-y-2.5">
              {(result.dosAndDonts?.dos || []).map((doItem, i) => (
                <li key={i} className="text-xs space-y-0.5">
                  <div className="font-semibold text-zinc-100 flex items-start gap-1.5">
                    <span className="text-emerald-400 font-bold">•</span>
                    <span>{doItem.title}</span>
                  </div>
                  <p className="text-[11px] text-zinc-400 pl-3 leading-relaxed">
                    {doItem.reason}
                  </p>
                </li>
              ))}
            </ul>
          </div>

          {/* DONT's Card */}
          <div className="p-4 bg-red-950/20 border border-red-500/30 rounded-xl space-y-3">
            <div className="flex items-center gap-2 pb-2 border-b border-red-500/20">
              <XCircle className="w-4 h-4 text-red-400 shrink-0" />
              <h4 className="text-xs font-bold uppercase tracking-wider text-red-300">
                ❌ Ye Galti Mat Karein (DONT's)
              </h4>
            </div>
            <ul className="space-y-2.5">
              {(result.dosAndDonts?.donts || []).map((dontItem, i) => (
                <li key={i} className="text-xs space-y-0.5">
                  <div className="font-semibold text-zinc-100 flex items-start gap-1.5">
                    <span className="text-red-400 font-bold">•</span>
                    <span>{dontItem.title}</span>
                  </div>
                  <p className="text-[11px] text-zinc-400 pl-3 leading-relaxed">
                    {dontItem.reason}
                  </p>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Pro Tips Bar */}
        {result.dosAndDonts?.proTips && (
          <div className="p-3 bg-zinc-950/80 border border-zinc-800 rounded-xl space-y-1.5 text-xs text-zinc-300">
            <div className="font-bold text-amber-400 text-[11px] uppercase tracking-wider flex items-center gap-1.5">
              <Zap className="w-3.5 h-3.5 fill-amber-400" />
              Secret Algorithm Hacks:
            </div>
            {result.dosAndDonts.proTips.map((tip, idx) => (
              <p key={idx} className="text-[11px] text-zinc-300 leading-relaxed">
                {tip}
              </p>
            ))}
          </div>
        )}
      </div>

      {/* Section 1: Ranked Title Suite for 1 Million Views */}
      <div className="bg-glass-card rounded-2xl p-5 sm:p-6 border border-zinc-800/80 shadow-xl space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-red-500/10 text-phonk-accent">
              <Crown className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm sm:text-base font-bold text-white flex items-center gap-2">
                1 Million Views Title Suite (Ranked by Algorithm Potential)
              </h3>
              <p className="text-xs text-zinc-400">
                Har title ke sath 1M+ views ka potential badge aur reason diya gaya hai
              </p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-3">
          {result.titles.map((titleObj, idx) => {
            const isWinner = idx === 0 || titleObj.millionViewsPotential?.rank === 'WINNER_1M';

            return (
              <div
                key={idx}
                className={`p-3.5 sm:p-4 rounded-xl border transition-all space-y-2 group ${
                  isWinner
                    ? 'bg-gradient-to-r from-red-950/30 via-zinc-900 to-zinc-900 border-phonk-accent/50 shadow-md'
                    : 'bg-zinc-950/80 border-zinc-800/80 hover:border-zinc-700'
                }`}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0 flex-1 space-y-1.5">
                    <div className="flex items-center gap-2 flex-wrap">
                      {titleObj.millionViewsPotential ? (
                        <span
                          className={`px-2 py-0.5 text-[10px] font-black uppercase rounded-md tracking-wider border shadow-sm ${
                            isWinner
                              ? 'bg-gradient-to-r from-phonk-accent to-red-600 text-white border-phonk-accent/50'
                              : 'bg-zinc-800 text-amber-300 border-amber-500/30'
                          }`}
                        >
                          {titleObj.millionViewsPotential.badge}
                        </span>
                      ) : (
                        <span className="px-2 py-0.5 text-[10px] font-bold uppercase rounded-md bg-zinc-800 text-zinc-300">
                          {titleObj.highlightTag || 'Viral Option'}
                        </span>
                      )}

                      <span className="text-[11px] text-zinc-400 font-medium">
                        {titleObj.hookType}
                      </span>
                      <span
                        className={`text-[10px] px-1.5 py-0.2 rounded font-mono ${
                          titleObj.charCount <= 75
                            ? 'text-emerald-400 bg-emerald-500/10'
                            : titleObj.charCount <= 95
                            ? 'text-amber-400 bg-amber-500/10'
                            : 'text-red-400 bg-red-500/10'
                        }`}
                      >
                        {titleObj.charCount} chars
                      </span>
                    </div>

                    <p className="text-sm sm:text-base font-bold text-zinc-100 group-hover:text-white transition-colors break-words">
                      {titleObj.title}
                    </p>
                  </div>

                  <button
                    onClick={() => handleCopyTitle(titleObj.title, idx)}
                    className="shrink-0 flex items-center gap-1 px-3 py-2 rounded-lg bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 hover:border-phonk-accent/50 text-xs font-semibold text-zinc-300 hover:text-white transition-all transform active:scale-95"
                  >
                    {copiedTitleIndex === idx ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                        <span className="text-emerald-400 text-[11px]">Copied</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5 text-zinc-400 group-hover:text-zinc-200" />
                        <span className="text-[11px]">Copy Title</span>
                      </>
                    )}
                  </button>
                </div>

                {/* 1M Views Reason Insight */}
                {titleObj.millionViewsPotential?.whyItHits1M && (
                  <div className="pt-1.5 border-t border-zinc-850 flex items-start gap-1.5 text-[11px] text-zinc-400">
                    <Target className="w-3.5 h-3.5 text-red-400 shrink-0 mt-0.5" />
                    <span>
                      <strong className="text-zinc-300">1M+ View Factor:</strong> {titleObj.millionViewsPotential.whyItHits1M}
                    </span>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Section 2: YouTube Studio Tags (500 Char limit) */}
      <div className="bg-glass-card rounded-2xl p-5 sm:p-6 border border-zinc-800/80 shadow-xl space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-purple-500/10 text-purple-400">
              <Tag className="w-4 h-4" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-sm sm:text-base font-bold text-white">
                  YouTube Studio Tags
                </h3>
                <span
                  className={`px-2 py-0.5 text-[11px] font-mono font-bold rounded-md border ${
                    result.tagsCharCount <= 495
                      ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
                      : 'bg-red-500/10 text-red-400 border-red-500/20'
                  }`}
                >
                  {result.tagsCharCount} / 500 characters
                </span>
              </div>
              <p className="text-xs text-zinc-400">
                Optimized keyword mix ready to paste straight into YouTube Studio
              </p>
            </div>
          </div>

          <button
            onClick={handleCopyTags}
            className="flex items-center justify-center gap-1.5 px-4 py-2 rounded-xl bg-purple-600/20 hover:bg-purple-600/30 border border-purple-500/40 text-purple-300 hover:text-purple-100 text-xs font-bold transition-all transform active:scale-95"
          >
            {copiedTags ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copiedTags ? 'Tags Copied!' : 'Copy Tags (Comma-Separated)'}</span>
          </button>
        </div>

        {/* Tag Pills */}
        <div className="p-4 bg-zinc-950/90 border border-zinc-800/80 rounded-xl">
          <div className="flex flex-wrap gap-1.5">
            {result.tags.map((tag, idx) => (
              <span
                key={idx}
                className="px-2.5 py-1 rounded-md bg-zinc-900 border border-zinc-800 text-xs text-zinc-300 font-medium"
              >
                {tag}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Section 3: High-Retention SEO Description */}
      <div className="bg-glass-card rounded-2xl p-5 sm:p-6 border border-zinc-800/80 shadow-xl space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-cyan-500/10 text-cyan-400">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm sm:text-base font-bold text-white">
                SEO-Friendly Video Description
              </h3>
              <p className="text-xs text-zinc-400">
                Includes track credits, subscribe CTA, fair-use disclaimer, and keyword clusters
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setIsEditingDesc(!isEditingDesc)}
              className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-zinc-900 border border-zinc-800 text-xs text-zinc-300 hover:text-white transition-colors"
            >
              <Edit3 className="w-3 h-3" />
              <span>{isEditingDesc ? 'Done' : 'Edit'}</span>
            </button>
            <button
              onClick={handleCopyDescription}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-cyan-600/20 hover:bg-cyan-600/30 border border-cyan-500/40 text-cyan-300 hover:text-cyan-100 text-xs font-bold transition-all transform active:scale-95"
            >
              {copiedDesc ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedDesc ? 'Description Copied!' : 'Copy Description'}</span>
            </button>
          </div>
        </div>

        {isEditingDesc ? (
          <textarea
            rows={8}
            value={editedDescription}
            onChange={(e) => setEditedDescription(e.target.value)}
            className="w-full px-4 py-3 bg-zinc-950 border border-cyan-500/50 rounded-xl text-xs sm:text-sm text-zinc-200 font-mono leading-relaxed focus:outline-none"
          />
        ) : (
          <pre className="p-4 bg-zinc-950/90 border border-zinc-800/80 rounded-xl text-xs sm:text-sm text-zinc-300 whitespace-pre-wrap font-sans leading-relaxed overflow-x-auto">
            {editedDescription}
          </pre>
        )}
      </div>

      {/* Section 4: Trending Hashtags */}
      <div className="bg-glass-card rounded-2xl p-5 border border-zinc-800/80 shadow-xl space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-amber-500/10 text-amber-400">
              <Hash className="w-4 h-4" />
            </div>
            <h3 className="text-sm font-bold text-white">Trending Phonk Hashtags</h3>
          </div>
          <button
            onClick={handleCopyHashtags}
            className="flex items-center gap-1 text-xs text-amber-400 hover:text-amber-300 font-semibold"
          >
            {copiedHashtags ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
            <span>{copiedHashtags ? 'Copied' : 'Copy All'}</span>
          </button>
        </div>
        <div className="flex flex-wrap gap-2">
          {result.hashtags.map((h, i) => (
            <button
              key={i}
              onClick={() => copyToClipboard(h, h)}
              className="px-3 py-1.5 bg-zinc-950 hover:bg-zinc-800 border border-zinc-800 hover:border-amber-500/40 rounded-lg text-xs font-semibold text-zinc-300 hover:text-amber-300 transition-all"
            >
              {h}
            </button>
          ))}
        </div>
      </div>

      {/* Section 6: AI Visual Edit & CapCut Frame Blueprint */}
      <VisualEditBlueprintCard
        blueprint={result.visualEditBlueprint}
        onShowToast={onShowToast}
      />

      {/* Section 7: A/B Title Battle Arena */}
      <TitleBattleArena titles={result.titles} onShowToast={onShowToast} />

      {/* Section 8: Live YouTube Shorts Mobile Feed Simulator */}
      <ShortsPreviewMockup
        titles={result.titles}
        channelName={result.input.channelName || 'PhnkEditz'}
        selectedTitleIndex={selectedPreviewTitleIdx}
        onSelectTitleIndex={(idx) => setSelectedPreviewTitleIdx(idx)}
        thumbnailHook={result.thumbnailHooks[0] || 'DONT BLINK 💀'}
        genre={result.input.genre}
      />

      {/* Section 9: Second-by-Second Retention Blueprint */}
      <RetentionTimeline />

      {/* Section 10: Audio BPM & Velocity Keyframe Sync Calculator */}
      <AudioSyncCalculator onShowToast={onShowToast} />
    </div>
  );
};
